
language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm run build

deploy:
  provider: pages
  local-dir: build
  target-branch: gh-pages
  email: tksudharshan@gmail.com
  name: tks18
  skip-cleanup: true
  github-token: $github-token
  keep-history: true
  on:
    branch: master